# Generated by Django 6.0 on 2025-12-30 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='worker',
            new_name='target',
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('client_to_worker', 'Client Reviewing Worker'), ('worker_to_client', 'Worker Reviewing Client')], default='client_to_worker', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('job', 'reviewer')},
        ),
    ]
