# Generated by Django 6.0 on 2026-05-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_worker_review_target_review_review_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='escrow_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Payment'), ('held', 'Funds Held'), ('released', 'Funds Released'), ('refunded', 'Refunded')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_method',
            field=models.CharField(default='simulated', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
