# Generated by Django 6.0 on 2026-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_escrow_status_job_paid_at_job_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='stripe_checkout_session_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='stripe_payment_intent_id',
            new_name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='job',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
