# Generated by Django 6.0 on 2026-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_stripe_checkout_session_id_job_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='urgency_level',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Emergency', 'Emergency')], default='Standard', max_length=20),
        ),
    ]
