# Generated by Django 6.0 on 2026-05-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('worker_completed', 'Worker Completed'), ('disputed', 'Disputed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
