# Generated by Django 6.0 on 2026-06-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_counter_budget_job_counter_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('worker_completed', 'Worker Completed'), ('disputed', 'Disputed'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
