# Generated by Django 6.0 on 2026-06-14 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('trade_category', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('experience', models.TextField()),
                ('availability', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('tools_equipment', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
