# Generated by Django 6.0 on 2026-06-14 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_workerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('trade_category', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Carpentry', 'Carpentry'), ('Electrical Work', 'Electrical Work'), ('Painting', 'Painting'), ('Cleaning / Deep Clean', 'Cleaning / Deep Clean'), ('Appliance Repair', 'Appliance Repair'), ('Gardening / Landscaping', 'Gardening / Landscaping'), ('Pest Control', 'Pest Control'), ('Masonry / Tiling', 'Masonry / Tiling'), ('AC & HVAC Servicing', 'AC & HVAC Servicing'), ('Moving & Heavy Lifting', 'Moving & Heavy Lifting'), ('Welding / Fabrication', 'Welding / Fabrication'), ('Interior Design Consultation', 'Interior Design Consultation'), ('Security & CCTV Installation', 'Security & CCTV Installation'), ('Computer / IT Repair', 'Computer / IT Repair')], max_length=50)),
                ('skills', models.TextField(help_text='List of skills and specializations')),
                ('experience_description', models.TextField(help_text='Past work experience described in text')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('availability', models.TextField(help_text='Days/hours generally available, e.g. Mon-Fri 9AM-5PM')),
                ('tools_equipment', models.TextField(blank=True, default='', help_text='Tools or equipment they own')),
                ('languages', models.CharField(blank=True, default='', help_text='Languages spoken', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Profile goes live only after required fields are filled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('worker', 'trade_category')},
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of work needed')),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(choices=[('09:00 AM - 10:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('12:00 PM - 01:00 PM', '12:00 PM - 01:00 PM'), ('01:00 PM - 02:00 PM', '01:00 PM - 02:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM - 04:00 PM', '03:00 PM - 04:00 PM'), ('04:00 PM - 05:00 PM', '04:00 PM - 05:00 PM'), ('05:00 PM - 06:00 PM', '05:00 PM - 06:00 PM')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('worker_notes', models.TextField(blank=True, default='', help_text='Counter-proposal or notes from worker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_service_requests', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_service_requests', to=settings.AUTH_USER_MODEL)),
                ('trade_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='profiles.tradeprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
