# Generated by Django 6.0 on 2026-06-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_tradeprofile_servicerequest_delete_workerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text="Worker's real-time latitude", null=True)),
                ('longitude', models.FloatField(blank=True, help_text="Worker's real-time longitude", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the worker currently accepting requests?')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
