# Generated by Django 6.0 on 2026-06-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='escrow_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Payment'), ('held', 'Funds Held'), ('released', 'Funds Released'), ('refunded', 'Refunded')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_method',
            field=models.CharField(default='simulated', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('worker_completed', 'Worker Completed'), ('disputed', 'Disputed'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
